### ISSUE TITLE
Wondering how to use this!

### ISSUE THREAD

**Issue by gordonbisnor** [jaydev/ember-cli-deploy-nanobox-redis-tunnel#1]
Hey I discovered this in the process of trying to figure out how to how a lightning deploy to Rails / Redis Nanobox app. From the sounds of it this plugin might do the trick –– any tips on how to use?

**Comment by gordonbisnor** [comment]
Okay so I looked over the index.js and added config to my deploy.js:

```javascript
'nanobox-redis-tunnel': {
  component: 'data.redis',
  remote: 'production'
}
```

Which started off with promise but then froze my terminal at:
```bash
Deploying [🚀 ----------------] 6% [plugin: nanobox-redis-tunnel -> setup]
```

I assume that this *is* working.... just need to figure out why it's hanging for me...

**Comment by jaydev** [comment]
Hey! Sorry, I haven't written a README yet. Is your `remote` parameter set to the app name you see when you run `nanobox remote ls`?

**Comment by gordonbisnor** [comment]
@jaydev Oh, i actually had set it to the alias name.... and then I realized as well that by ember application was not connected to the Nanobox, so I switched my remote config to use the actual app name, then run ```nanobox remote add xxx xxx` within my ember app and it is is sort of working for me! 

The only thing I have not figured out though is that in my config/deploy.js file I am specifying different remotes for staging and production, but it seems to be deploying to the wrong remote somehow, eg if I first run: 

```bash
ember deploy production --activate=true
``` 

my production app is working great, but then when I run this: 

```bash
ember deploy staging --activate=true
``` 

my production app is now calling the staging API... 

First of all, I should say thanks for writing this library!

**Comment by gordonbisnor** [comment]
So what seems to be happening is that if I deploy to production, a nanobox tunnel is opened. It works great. But after deploy the tunnel remains open, and when I then deploy to staging, it must be using the existing tunnel. So perhaps the teardown is not getting called or working for some reason and/or I wonder if it should kill any existing tunnel when it deploys just to be sure?

**Comment by jaydev** [comment]
I have had the same problem a couple times, but it seems to come and go. Most of the time it just works. Sometimes I run `ps aux | grep --color redis` to make sure the tunnel is closed.

Are you running your builds in parallel? I'm not super familiar with Node's process spawning model but that could cause the problem.

Currently this is how the tunnel is closed:
```js
teardown(context) {
  this.log('Closing Redis tunnel', {verbose: true});
  context.tunnel.kill('SIGTERM');
}
```

`SIGTERM` allows the process to close itself but there is no guarantee when the process will end. If you know of a better way of killing the tunnel I would love to hear it.

**Comment by gordonbisnor** [comment]
@jaydev I tried forking this and using SIGKILL, which seems like it may be working for me –– I will try switching back and forth between SIGTERM  and SIGKILL to see if I can consistently reproduce the same results!

**Comment by gordonbisnor** [comment]
@jaydev Tried switching between SIGKILL and SIGTERM but both seem to work identically – I'm thinking that I may have had a really flaky internet connection yesterday that might have caused my issues.

I would be happy to do add a README if you like for this!

**Comment by jaydev** [comment]
> I would be happy to do add a README if you like for this!

Yeah, that would be great!

**Comment by gordonbisnor** [comment]
@jaydev Okay - did a pull request!
